from django.urls import path
from . import views

app_name = 'waiss'

urlpatterns = [
     path('', views.index, name='index'),
     path('input-calibration-constants/', views.calib, name='calib'),
     path('about/', views.about, name='about'),
     path('charts/', views.charts, name='charts'),
     path('add-farm/', views.farm_account, name='farmaccount'),
     path('add-soil-parameters/', views.add_soil, name='addsoil'),
     path('add-sensor/', views.add_sensor, name='addsensor'),
     path('add-fieldunit/', views.add_fieldunit, name='addfieldunit'),
     path('add-intakefamily/', views.add_intake, name='intakefamily'),
     path('add-advisorysettings/',views.add_personnel, name='advisorysettings'),
     path('add-crop-parameters/', views.crop_info, name='cropinfo'),
     path('add-fieldunit-settings/', views.field_unit_settings, name='fieldunitsettings'),
     path('select-irrig-type/', views.choose_irrig, name='irriginfo'),
     path('select-irrig-type-database/', views.choose_irrig_database, name='choose-irrigation-system-type'),
     path('show-irrig-calculations/', views.irrig_calculations, name='irrig-calculations'),
     path('show-farm-summary/', views.farm_summaries, name='farmsummaries'),
     path('show-soil-database/', views.select_soil, name='select_soil'),
     path('show-crop-database/', views.select_crop, name='select_crop'),
     path('show-calib-equations-database/',views.select_eqn, name='select_eqn'),
     path('show_intakefamily/-database', views.select_intakefamily, name='select_intakefamily'),
     path('show-fieldunit-database/', views.fieldunit_list_view, name='fieldunitslist'),
     path('show-farm-database/', views.farm_list_view, name='farmlist'),
     path('show-sensor-database/', views.sensor_list_view, name='sensorlist'),
     path('show-personnel-database/', views.personnel_list_view, name='personnellist'),
     path('add-basin-system/', views.add_basin, name='addbasin'),
     path('add-border-system/', views.add_border, name='addborder'),
     path('add-furrow-system/', views.add_furrow, name='addfurrow'),
     path('add-drip-system/', views.add_drip, name='adddrip'),
     path('add-sprinkler-system/', views.add_sprinkler, name='addsprinkler'),
     path('show-basin-database/', views.basin_list, name='listbasin'),
     path('show-border-database/', views.border_list, name='listborder'),
     path('show-furrow-database/', views.furrow_list, name='listfurrow'),
     path('show-drip-database/', views.drip_list, name='listdrip'),
     path('show-sprinkler-database/', views.sprinkler_list, name='listsprinkler'),
]