# Generated by Django 3.0.8 on 2020-07-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0003_auto_20200708_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldunit',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm'),
        ),
    ]
