# Generated by Django 3.0.8 on 2020-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0005_auto_20200708_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
