# Generated by Django 3.0.8 on 2020-07-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0006_auto_20200708_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm'),
        ),
        migrations.AddField(
            model_name='crop',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AddField(
            model_name='intakefamily',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm'),
        ),
        migrations.AddField(
            model_name='intakefamily',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AddField(
            model_name='soil',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm'),
        ),
        migrations.AddField(
            model_name='soil',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='usk',
            field=models.CharField(max_length=8, verbose_name='Unique Security Key'),
        ),
        migrations.AlterField(
            model_name='sensornumber',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Sensor Name'),
        ),
    ]
