# Generated by Django 3.0.8 on 2020-07-09 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0008_auto_20200709_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Fn',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Mc1',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Mc2',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Mc3',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='McToIrrigate',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Ta',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Ti',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Tn',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='Tt',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='appeff',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='eff_adv_ratio',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='length',
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='application_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Application Rate (lps/sq.m)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='area_irrigated_at_a_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Area irrigated at a time (sq.m)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='bln_operating_pressure',
            field=models.BooleanField(default=True, verbose_name='Is the operating pressure known?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='discharge_coefficient',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Discharge Coefficient'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='ea',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='farm_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Farm area (sq.m)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='gross_app_depth',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Gross Application Depth (mm)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='irrigation_period',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Irrigation Peiod (mins)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='irrigation_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Irrigation Rate (lps/sq.m)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='lateral_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Lateral spacing (m)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='net_app_depth',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Net Application Depth (mm)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='nozzle_dia',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Nozzle diameter (mm)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='num_of_sprinklers',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Number of sprinklers'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='operating_pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Operating Pressure (kPa)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='sprinkler_discharge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler Discharge (lps)'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='sprinkler_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler spacing (m)'),
        ),
        migrations.AlterField(
            model_name='dripcomp',
            name='emitter_coeff',
            field=models.DecimalField(decimal_places=2, help_text='Input emitter coefficient if known.', max_digits=5, null=True, verbose_name='Emitter coefficient'),
        ),
        migrations.AlterField(
            model_name='dripcomp',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field unit'),
        ),
        migrations.AlterField(
            model_name='dripcomp',
            name='optimum_emitter_spacing',
            field=models.DecimalField(decimal_places=2, help_text='This is only computed for non-single straight lateral system.', max_digits=5, null=True, verbose_name='Optimum Emitter Spacing (m)'),
        ),
        migrations.AlterField(
            model_name='sprinklercomp',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field unit'),
        ),
    ]
