# Generated by Django 3.0.8 on 2020-07-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0009_auto_20200709_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basincomp',
            name='Fn',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='Mc1',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='Mc2',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='Mc3',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='McToIrrigate',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='Ta',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='Ti',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='Tn',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='Tt',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='appeff',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='length',
        ),
        migrations.AddField(
            model_name='basincomp',
            name='advance_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Advance Time (mins)'),
        ),
        migrations.AddField(
            model_name='basincomp',
            name='basin_length',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Basin Length (m)'),
        ),
        migrations.AddField(
            model_name='basincomp',
            name='ea',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Ea (%)'),
        ),
        migrations.AddField(
            model_name='basincomp',
            name='inflow_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Inflow Time (mins)'),
        ),
        migrations.AddField(
            model_name='basincomp',
            name='irrigation_period',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Irrigation Period (mins)'),
        ),
        migrations.AddField(
            model_name='basincomp',
            name='net_app_depth',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Net Application Depth (mm)'),
        ),
        migrations.AddField(
            model_name='basincomp',
            name='net_opp_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Net Opportunity Time (mins)'),
        ),
        migrations.AlterField(
            model_name='basincomp',
            name='discharge',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='sprinklercomp',
            name='discharge_coefficient',
            field=models.DecimalField(decimal_places=2, help_text='Fill-out only if operating pressure is known.', max_digits=5, null=True, verbose_name='Discharge Coefficient'),
        ),
        migrations.AlterField(
            model_name='sprinklercomp',
            name='irrigation_period',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Irrigation Period (mins)'),
        ),
        migrations.AlterField(
            model_name='sprinklercomp',
            name='nozzle_dia',
            field=models.DecimalField(decimal_places=2, help_text='Fill-out only if operating pressure is known.', max_digits=5, null=True, verbose_name='Nozzle diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='sprinklercomp',
            name='sprinkler_discharge',
            field=models.DecimalField(decimal_places=2, help_text='Fill-out if operating pressure is unknown.', max_digits=5, null=True, verbose_name='Sprinkler Discharge (lps)'),
        ),
    ]
