# Generated by Django 3.0.8 on 2020-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0010_auto_20200709_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Fn',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Mc1',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Mc2',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Mc3',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='McToIrrigate',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Ta',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Ti',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Tn',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='Tt',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='appeff',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='eff_adv_ratio',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='length',
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='advance_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Advance Time (mins)'),
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='area_slope',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Slope'),
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='bln_furrow_type',
            field=models.BooleanField(default=True, verbose_name='It is an open-ended furrow.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='irrigation_period',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Irrigation Period (mins)'),
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='net_app_depth',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Net Application Depth (mm)'),
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='net_opp_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Net Opportunity Time (mins)'),
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='p_adjusted',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='P adjusted (m)'),
        ),
        migrations.AlterField(
            model_name='basincomp',
            name='ea',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='furrowcomp',
            name='discharge',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
    ]
