# Generated by Django 3.0.8 on 2020-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0011_auto_20200709_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordercomp',
            name='Fn',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='Mc1',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='Mc2',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='Mc3',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='McToIrrigate',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='Ta',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='Ti',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='Tn',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='Tt',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='appeff',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='eff_adv_ratio',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='length',
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='area_slope',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Slope'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='border_width',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Border Width (m)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='ea',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='flow_rate_per_strip',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Flow rate per border strip (lps)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='inflow_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Inflow Time (mins)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='irrigation_period',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Irrigation Period (mins)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='lag_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Lag Time (mins)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='mannings_coeff',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name="Manning's coefficient"),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='net_app_depth',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Net Application Depth (mm)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='net_opp_time',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Net Opportunity Time (mins)'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='num_of_border_strips',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Number of Borders'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='total_flow_rate',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Total flow rate (lps)'),
        ),
        migrations.AlterField(
            model_name='bordercomp',
            name='discharge',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
    ]
