# Generated by Django 3.0.8 on 2020-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0013_auto_20200714_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_location',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='first_name',
            field=models.CharField(default=True, max_length=30, verbose_name="Farm Manager's First Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='last_name',
            field=models.CharField(default=True, max_length=30, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
