# Generated by Django 3.0.8 on 2020-07-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0014_auto_20200714_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='soil',
            name='fieldunit',
        ),
    ]
