# Generated by Django 3.0.8 on 2020-07-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0015_auto_20200716_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldunit',
            options={'verbose_name_plural': 'Site: Field Units'},
        ),
        migrations.RemoveField(
            model_name='fieldunit',
            name='timestamp',
        ),
    ]
