# Generated by Django 3.0.8 on 2020-07-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0016_auto_20200716_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='last_name',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel', verbose_name='Farm Manager'),
        ),
    ]
