# Generated by Django 3.0.8 on 2020-07-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0017_auto_20200721_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmsummaries',
            name='As',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='McToIrrig',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='appeff',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='calib_coeff_a',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='calib_coeff_b',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='calib_coeff_c',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='calib_coeff_d',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='calib_coeff_m',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='coeff_a',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='coeff_b',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='coeff_c',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='coeff_f',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='coeff_g',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='date_transplanted',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='depletionfactor',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='drz',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='eff_adv_ratio',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='growingperiod',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='kc_cc_1',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='kc_cc_2',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='kc_cc_3',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='kc_end',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='kc_ini',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='kc_mid',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='mad',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='pwp',
        ),
        migrations.AddField(
            model_name='calibrationconstant',
            name='calib_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Calibration Name'),
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='calib_eqn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.CalibrationConstant'),
        ),
    ]
