# Generated by Django 3.0.8 on 2020-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0018_auto_20200721_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensornumber',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='sensornumber',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5, verbose_name='Depth, m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_equation',
            field=models.CharField(choices=[('LIN', 'Linear'), ('QUA', 'Quadratic'), ('SSIG', 'Symmetrical Sigmoidal'), ('ASSIG', 'Asymmetrical Sigmoidal'), ('EXP', 'Exponential'), ('POW', 'Power'), ('LOG', 'Logarithmic')], default='LIN', max_length=5, verbose_name='Calibration Equation Form'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='farm_irrigation',
            field=models.CharField(choices=[('BAS', 'Basin'), ('BOR', 'Border'), ('FUR', 'Furrow'), ('SPR', 'Sprinkler'), ('DRI', 'Drip')], max_length=3, verbose_name='Irrigation System'),
        ),
    ]
