# Generated by Django 3.0.8 on 2020-07-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0019_auto_20200721_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moisturecontent',
            name='farm_name',
        ),
        migrations.AlterField(
            model_name='sensornumber',
            name='depth',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Depth, m'),
        ),
    ]
