# Generated by Django 3.0.8 on 2020-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0020_auto_20200728_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='basincomp',
            name='basin_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basincomp',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
    ]
