# Generated by Django 3.0.8 on 2020-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0022_auto_20200728_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basincomp',
            name='basin_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='bordercomp',
            name='border_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='dripcomp',
            name='bln_prefers_irrig_interval',
            field=models.BooleanField(verbose_name='Have preffered irrigation interval.'),
        ),
        migrations.AlterField(
            model_name='dripcomp',
            name='bln_single_lateral',
            field=models.BooleanField(verbose_name='Is a Single Straight Lateral type.'),
        ),
        migrations.AlterField(
            model_name='furrowcomp',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='sprinklercomp',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
    ]
