# Generated by Django 3.0.8 on 2020-07-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0023_auto_20200728_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='dripcomp',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
    ]
