# Generated by Django 3.0.7 on 2020-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0026_auto_20200806_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drippara',
            name='wetted_width',
        ),
        migrations.AlterField(
            model_name='drippara',
            name='wetted_dia',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Wetted diameter (m)'),
        ),
    ]
