# Generated by Django 3.0.8 on 2020-08-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0028_auto_20200813_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='farm_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm'),
        ),
        migrations.AddField(
            model_name='soil',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
    ]
