# Generated by Django 3.0.8 on 2020-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0029_auto_20200813_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='source',
            field=models.CharField(max_length=30, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soiltype',
            field=models.CharField(max_length=25, verbose_name='Soil Type'),
        ),
    ]
