# Generated by Django 3.0.8 on 2020-08-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0030_auto_20200813_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='source',
            field=models.CharField(max_length=30, null=True, verbose_name='Data Source'),
        ),
    ]
