# Generated by Django 3.0.8 on 2020-08-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0031_auto_20200813_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm', verbose_name='Farm Name'),
        ),
        migrations.AddField(
            model_name='crop',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit Name'),
        ),
        migrations.AddField(
            model_name='intakefamily',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm', verbose_name='Farm Name'),
        ),
        migrations.AddField(
            model_name='intakefamily',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit Name'),
        ),
    ]
