# Generated by Django 3.0.8 on 2020-08-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0032_auto_20200814_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ('crop',), 'verbose_name_plural': 'Database: Crop'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ('farm_name',), 'verbose_name_plural': 'Site: Farms'},
        ),
        migrations.AlterModelOptions(
            name='fieldunit',
            options={'ordering': ('name',), 'verbose_name_plural': 'Site: Field Units'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ('last_name',), 'verbose_name_plural': 'Site: Personnel'},
        ),
        migrations.AlterModelOptions(
            name='soil',
            options={'ordering': ('soiltype',), 'verbose_name_plural': 'Database: Soil'},
        ),
        migrations.AddField(
            model_name='intakefamily',
            name='soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Soil', verbose_name='Soil'),
        ),
        migrations.AddField(
            model_name='intakefamily',
            name='source',
            field=models.CharField(max_length=30, null=True, verbose_name='Data Source'),
        ),
    ]
