# Generated by Django 3.0.8 on 2020-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0033_auto_20200817_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationconstant',
            old_name='soiltype',
            new_name='soil',
        ),
        migrations.AddField(
            model_name='calibrationconstant',
            name='date_tested',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Calibrated'),
        ),
        migrations.AddField(
            model_name='calibrationconstant',
            name='tested_by',
            field=models.CharField(max_length=30, null=True, verbose_name='Tested By'),
        ),
    ]
