# Generated by Django 3.0.8 on 2020-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0034_auto_20200817_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldunitsettings',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Settings Name'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_a',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_b',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='m'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='tested_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tested By'),
        ),
    ]
