# Generated by Django 3.0.8 on 2020-08-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0035_auto_20200818_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basinpara',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='basinpara',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='borderpara',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='borderpara',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='calibrationconstant',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='calibrationconstant',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='calibrationconstant',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='drippara',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='drippara',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='farmsummaries',
            name='farm_irrigation',
        ),
        migrations.RemoveField(
            model_name='furrowpara',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='furrowpara',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='sprinklerpara',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='sprinklerpara',
            name='fieldunit',
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='basin_sys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BasinPara'),
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='border_sys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BorderPara'),
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='drip_sys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.DripPara'),
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='furrow_sys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FurrowPara'),
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='sprinkler_sys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.SprinklerPara'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Field Unit Name'),
        ),
        migrations.AlterField(
            model_name='intakefamily',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='intakefamily',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
    ]
