# Generated by Django 3.0.8 on 2020-08-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0036_auto_20200820_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmsummaries',
            name='soiltype',
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='intakefamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.IntakeFamily'),
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Soil'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='basin_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BasinPara'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='border_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BorderPara'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='calib_eqn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.CalibrationConstant'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Crop'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='drip_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.DripPara'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='furrow_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FurrowPara'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='sprinkler_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.SprinklerPara'),
        ),
    ]
