# Generated by Django 3.0.8 on 2020-08-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0037_auto_20200820_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basincomp',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='dripcomp',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='dripcomp',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='fieldunit',
        ),
        migrations.AddField(
            model_name='basincomp',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FarmSummaries'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FarmSummaries'),
        ),
        migrations.AddField(
            model_name='dripcomp',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FarmSummaries'),
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FarmSummaries'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FarmSummaries'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='basin_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BasinPara', verbose_name='Basin Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='border_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BorderPara', verbose_name='Border Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='calib_eqn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.CalibrationConstant', verbose_name='Calibration'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='drip_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.DripPara', verbose_name='Drip Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel', verbose_name='Farm Manager'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='furrow_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FurrowPara', verbose_name='Furrow Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='intakefamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.IntakeFamily', verbose_name='Intake Family'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='sprinkler_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.SprinklerPara', verbose_name='Sprinkler Irrigation'),
        ),
    ]
