# Generated by Django 3.0.8 on 2020-08-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0041_auto_20200824_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldunit',
            options={'verbose_name_plural': 'Site: Field Units'},
        ),
        migrations.AlterModelOptions(
            name='sensornumber',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'Site: Sensors'},
        ),
        migrations.RenameField(
            model_name='moisturecontent',
            old_name='data_storage',
            new_name='sensor',
        ),
        migrations.RemoveField(
            model_name='fieldunit',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='moisturecontent',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm'),
        ),
        migrations.AddField(
            model_name='sensornumber',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Measured'),
        ),
    ]
