# Generated by Django 3.0.8 on 2020-08-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0042_auto_20200824_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moisturecontent',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'Site: Sensor Readings'},
        ),
        migrations.AlterModelOptions(
            name='sensornumber',
            options={'verbose_name_plural': 'Site: Sensors'},
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_manager',
        ),
        migrations.RemoveField(
            model_name='moisturecontent',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='sensornumber',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='moisturecontent',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Measured'),
        ),
    ]
