# Generated by Django 3.0.8 on 2020-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0043_auto_20200824_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='eqnform',
            field=models.CharField(choices=[('linear', 'linear'), ('quadratic', 'quadratic')], max_length=20, null=True, verbose_name='Equation Form'),
        ),
        migrations.AddField(
            model_name='crop',
            name='root_a',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True, verbose_name='a'),
        ),
        migrations.AddField(
            model_name='crop',
            name='root_b',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True, verbose_name='b'),
        ),
        migrations.AddField(
            model_name='crop',
            name='root_c',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True, verbose_name='c'),
        ),
        migrations.AddField(
            model_name='crop',
            name='root_ini',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True, verbose_name='Root Depth during Transplant (m)'),
        ),
    ]
