# Generated by Django 3.0.8 on 2020-09-15 06:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0044_auto_20200825_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dripcomp',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'Computation: Drip'},
        ),
        migrations.RenameField(
            model_name='moisturecontent',
            old_name='sensor',
            new_name='sensor_name',
        ),
        migrations.RenameField(
            model_name='sensornumber',
            old_name='name',
            new_name='sensor_name',
        ),
        migrations.RemoveField(
            model_name='basinpara',
            name='eff_adv_ratio',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='depletionfactor',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_location',
        ),
        migrations.RemoveField(
            model_name='fieldunit',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='fieldunitsettings',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='basincomp',
            name='eff_adv_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='dripcomp',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Measured'),
        ),
        migrations.AddField(
            model_name='farm',
            name='brgy',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='farm',
            name='lat',
            field=models.DecimalField(blank='True', decimal_places=6, max_digits=9, null='True', verbose_name='Latitude (deg)'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='farm',
            name='long',
            field=models.DecimalField(blank='True', decimal_places=6, max_digits=9, null='True', verbose_name='Longitude (deg)'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='farm',
            name='municipality',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='farm',
            name='province',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='farmsummaries',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnitSettings', verbose_name='Settings'),
        ),
        migrations.AlterField(
            model_name='basinpara',
            name='basin_length',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Basin Length (m)'),
        ),
        migrations.AlterField(
            model_name='basinpara',
            name='basin_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Basin Irrigation System Filename'),
        ),
        migrations.AlterField(
            model_name='basinpara',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='basinpara',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, help_text='Application efficiency is the fraction of the irrigation water that is used by the crop. Provided there are no runoff losses, the application efficiency (%) is the required irrigation depth (mm), divided by the average applied irrigation depth (mm), multiplied by 100%.', max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='area_slope',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Slope'),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='border_width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Border Width (m)'),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='ea',
            field=models.DecimalField(blank=True, choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='flow_rate_per_strip',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Flow rate per border strip (lps)'),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='mannings_coeff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name="Manning's coefficient"),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='num_of_border_strips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Number of Borders'),
        ),
        migrations.AlterField(
            model_name='borderpara',
            name='total_flow_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Total flow rate (lps)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='date_transplanted',
            field=models.DateField(blank=True, null=True, verbose_name='Date Transplanted'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='eqnform',
            field=models.CharField(blank=True, choices=[('linear', 'linear'), ('quadratic', 'quadratic')], max_length=20, null=True, verbose_name='Equation Form'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc curve cutoff (1)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc curve cutoff (2)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc curve cutoff (3)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (end)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (ini)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (mid)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_a',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_b',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_c',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' c'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_ini',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Root Depth during Transplant (m)'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='EU',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True, verbose_name='Design Emission Uniformity'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='emitter_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Emitter Spacing (m)'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='emitters_per_plant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='No. of Emitters per Plant'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='irrigation_interval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Irrigation Interval (days)'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='plant_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Plant spacing (m)'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='row_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Row spacing (m)'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='wetted_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wetted diameter (m)'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='basin_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BasinPara', verbose_name='Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='border_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BorderPara', verbose_name='Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='drip_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.DripPara', verbose_name='Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel', verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='furrow_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FurrowPara', verbose_name='Irrigation'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique='True', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='farmsummaries',
            name='sprinkler_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.SprinklerPara', verbose_name='Irrigation'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='clockcorrection',
            field=models.TimeField(blank=True, null=True, verbose_name='Clock Correction'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='delay',
            field=models.TimeField(blank=True, null=True, verbose_name='Sending Delay'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='fieldunitnumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='sensorintegrationtime',
            field=models.TimeField(verbose_name='Sensor Integration Time'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='servernumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='timestart',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting Time'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='timestop',
            field=models.TimeField(blank=True, null=True, verbose_name='Stopping Time'),
        ),
        migrations.AlterField(
            model_name='furrowpara',
            name='area_slope',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Slope'),
        ),
        migrations.AlterField(
            model_name='furrowpara',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='sprinklerpara',
            name='area_irrigated_at_a_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Area irrigated at a time (sq.m)'),
        ),
        migrations.AlterField(
            model_name='sprinklerpara',
            name='ea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency'),
        ),
        migrations.AlterField(
            model_name='sprinklerpara',
            name='farm_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Farm area (sq.m)'),
        ),
        migrations.AlterField(
            model_name='sprinklerpara',
            name='lateral_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lateral spacing (m)'),
        ),
        migrations.AlterField(
            model_name='sprinklerpara',
            name='num_of_sprinklers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Number of sprinklers'),
        ),
        migrations.AlterField(
            model_name='sprinklerpara',
            name='sprinkler_discharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='sprinklerpara',
            name='sprinkler_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler spacing (m)'),
        ),
    ]
