# Generated by Django 3.0.8 on 2020-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0044_auto_20200825_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dripcomp',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'Computation: Drip'},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='depletionfactor',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fieldunit',
        ),
        migrations.AddField(
            model_name='dripcomp',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Measured'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='eqnform',
            field=models.CharField(blank=True, choices=[('linear', 'linear'), ('quadratic', 'quadratic')], max_length=20, null=True, verbose_name='Equation Form'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc curve cutoff (1)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc curve cutoff (2)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc curve cutoff (3)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (end)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (ini)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (mid)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_a',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_b',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_c',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' c'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_ini',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Root Depth during Transplant (m)'),
        ),
    ]
