# Generated by Django 3.0.8 on 2020-08-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0045_auto_20200825_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='clockcorrection',
            field=models.TimeField(blank=True, null=True, verbose_name='Clock Correction'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='delay',
            field=models.TimeField(blank=True, null=True, verbose_name='Sending Delay'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='sensorintegrationtime',
            field=models.TimeField(verbose_name='Sensor Integration Time'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='timestart',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting Time'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='timestop',
            field=models.TimeField(blank=True, null=True, verbose_name='Stopping Time'),
        ),
    ]
