# Generated by Django 3.0.8 on 2020-09-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0045_auto_20200915_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornumber',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldunits', to='waissapp.FieldUnit'),
        ),
        migrations.AlterModelTable(
            name='fieldunit',
            table='fieldunits',
        ),
        migrations.AlterModelTable(
            name='sensornumber',
            table='sensors',
        ),
    ]
