# Generated by Django 3.0.8 on 2020-08-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0046_auto_20200827_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldunitsettings',
            name='farm_name',
        ),
    ]
