# Generated by Django 3.0.8 on 2020-09-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0046_auto_20200915_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='long',
            new_name='longi',
        ),
        migrations.RemoveField(
            model_name='calibrationconstant',
            name='sensor',
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_a',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_b',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' c'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' d'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_coeff_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' m'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_equation',
            field=models.CharField(choices=[('LIN', 'Linear'), ('QUA', 'Quadratic'), ('SSIG', 'Symmetrical Sigmoidal'), ('ASSIG', 'Asymmetrical Sigmoidal'), ('EXP', 'Exponential'), ('POW', 'Power'), ('LOG', 'Logarithmic')], default='LIN', max_length=5, verbose_name='Equation Form'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='brgy',
            field=models.CharField(blank='True', max_length=50, null='True', verbose_name='Barangay'),
        ),
    ]
