# Generated by Django 3.0.8 on 2020-08-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0047_remove_fieldunitsettings_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='date_transplanted',
            field=models.DateField(blank=True, null=True, verbose_name='Date Transplanted'),
        ),
    ]
