# Generated by Django 3.0.8 on 2020-09-18 05:30

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0047_auto_20200918_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='SentMsgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=200)),
                ('usk', models.CharField(max_length=8, verbose_name='Unique Security Key')),
                ('sender_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('fieldunit_number', models.CharField(max_length=8, verbose_name='Unique Security Key')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Time Sent')),
                ('receiver_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Receiver', verbose_name='Sender')),
            ],
            options={
                'verbose_name_plural': 'Messages: Sent',
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='ReceivedMsgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=200)),
                ('usk', models.CharField(max_length=8, verbose_name='Unique Security Key')),
                ('fieldunit_number', models.CharField(max_length=8, verbose_name='Unique Security Key')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Time Sent')),
                ('receiver_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Receiver', verbose_name='Sender')),
                ('sender_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Sender', verbose_name='Sender')),
            ],
            options={
                'verbose_name_plural': 'Messages: Received',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
