# Generated by Django 3.0.8 on 2020-09-18 06:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0049_auto_20200918_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasinAppEff',
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='fieldunit_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='receiver_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Receiver', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date/Time Sent'),
        ),
    ]
