# Generated by Django 3.0.8 on 2020-09-24 07:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0050_auto_20200918_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='root_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Root Depth during Transplant (m)'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='fieldunitnumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Field Unit Number'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='sensorintegrationtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Sensor Integration Time'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='servernumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Server Number'),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='fieldunit_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='receiver_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Receiver', verbose_name='Receiver'),
        ),
    ]
