# Generated by Django 3.0.8 on 2020-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0051_auto_20200924_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='clockcorrection',
            field=models.DurationField(blank=True, null=True, verbose_name='Clock Correction'),
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='delay',
            field=models.DurationField(blank=True, null=True, verbose_name='Sending Delay'),
        ),
    ]
