# Generated by Django 3.0.8 on 2020-10-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0053_crop_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='soil',
            name='fieldunit',
        ),
        migrations.AlterField(
            model_name='crop',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Data Source'),
        ),
    ]
