# Generated by Django 3.0.8 on 2020-11-03 02:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0054_auto_20201002_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldunitsettings',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='basincomp',
            name='system',
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='system',
        ),
        migrations.RemoveField(
            model_name='dripcomp',
            name='system',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='system',
        ),
        migrations.RemoveField(
            model_name='intakefamily',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='intakefamily',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='intakefamily',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='system',
        ),
        migrations.AddField(
            model_name='basincomp',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AddField(
            model_name='bordercomp',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AddField(
            model_name='dripcomp',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AddField(
            model_name='farm',
            name='basin_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BasinPara', verbose_name='Irrigation'),
        ),
        migrations.AddField(
            model_name='farm',
            name='border_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.BorderPara', verbose_name='Irrigation'),
        ),
        migrations.AddField(
            model_name='farm',
            name='calib_eqn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.CalibrationConstant', verbose_name='Calibration'),
        ),
        migrations.AddField(
            model_name='farm',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Crop'),
        ),
        migrations.AddField(
            model_name='farm',
            name='drip_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.DripPara', verbose_name='Irrigation'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='farm',
            name='furrow_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FurrowPara', verbose_name='Irrigation'),
        ),
        migrations.AddField(
            model_name='farm',
            name='intakefamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.IntakeFamily', verbose_name='Intake Family'),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Soil'),
        ),
        migrations.AddField(
            model_name='farm',
            name='sprinkler_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.SprinklerPara', verbose_name='Irrigation'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='automaticthreshold',
            field=models.BooleanField(default=True, verbose_name='Automatic Threshold (?)'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='clockcorrection',
            field=models.DurationField(blank=True, null=True, verbose_name='Clock Correction'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='delay',
            field=models.DurationField(blank=True, null=True, verbose_name='Sending Delay'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='fieldunitnumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Field Unit Number'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='fieldunitstatus',
            field=models.BooleanField(default=True, verbose_name='Field Unit Status'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='numberofsamples',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='No. of Samples'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='sensorintegrationtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Sensor Integration Time'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='servernumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Server Number'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='timestart',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting Time'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='timestop',
            field=models.TimeField(blank=True, null=True, verbose_name='Stopping Time'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='usk',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Unique Security Key'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='withirrigation',
            field=models.BooleanField(default=True, verbose_name='With Irrigation (?)'),
        ),
        migrations.AddField(
            model_name='furrowcomp',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AddField(
            model_name='sprinklercomp',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='usk',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Unique Security Key'),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='usk',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Unique Security Key'),
        ),
        migrations.DeleteModel(
            name='FarmSummaries',
        ),
        migrations.DeleteModel(
            name='FieldUnitSettings',
        ),
    ]
