# Generated by Django 3.0.8 on 2020-11-03 03:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0055_auto_20201103_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUnitSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Settings Name')),
                ('usk', models.CharField(max_length=8, verbose_name='Unique Security Key')),
                ('fieldunitstatus', models.BooleanField(default=True, verbose_name='Field Unit Status')),
                ('withirrigation', models.BooleanField(default=True, verbose_name='With Irrigation (?)')),
                ('automaticthreshold', models.BooleanField(default=True, verbose_name='Automatic Threshold (?)')),
                ('servernumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Server Number')),
                ('fieldunitnumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Field Unit Number')),
                ('numberofsamples', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='No. of Samples')),
                ('sensorintegrationtime', models.TimeField(blank=True, null=True, verbose_name='Sensor Integration Time')),
                ('timestart', models.TimeField(blank=True, null=True, verbose_name='Starting Time')),
                ('timestop', models.TimeField(blank=True, null=True, verbose_name='Stopping Time')),
                ('delay', models.DurationField(blank=True, null=True, verbose_name='Sending Delay')),
                ('clockcorrection', models.DurationField(blank=True, null=True, verbose_name='Clock Correction')),
                ('fieldunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit')),
            ],
            options={
                'verbose_name_plural': 'Site: Field Unit Settings',
            },
        ),
    ]
