# Generated by Django 3.0.8 on 2020-11-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0056_fieldunitsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldunitsettings',
            name='fieldunit',
        ),
        migrations.AlterField(
            model_name='fieldunitsettings',
            name='sensorintegrationtime',
            field=models.DurationField(blank=True, null=True, verbose_name='Sensor Integration Time'),
        ),
    ]
