# Generated by Django 3.0.8 on 2020-11-04 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0057_auto_20201103_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AddField(
            model_name='farm',
            name='raw_data',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Analog Reading'),
        ),
        migrations.AddField(
            model_name='farm',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnitSettings', verbose_name='Settings'),
        ),
    ]
