# Generated by Django 3.0.8 on 2020-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0058_auto_20201104_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='settings',
        ),
        migrations.AlterField(
            model_name='farm',
            name='raw_data',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Analog Reading'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='numberofsamples',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='No. of Samples'),
        ),
        migrations.DeleteModel(
            name='FieldUnitSettings',
        ),
    ]
