# Generated by Django 3.0.8 on 2020-11-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0059_auto_20201104_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='longi',
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='lat',
            field=models.DecimalField(blank='True', decimal_places=6, max_digits=9, null='True', verbose_name='Latitude (°)'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='longi',
            field=models.DecimalField(blank='True', decimal_places=6, max_digits=9, null='True', verbose_name='Longitude (°)'),
            preserve_default='True',
        ),
    ]
