# Generated by Django 3.0.8 on 2020-11-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0061_farm_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldunit',
            name='clockcorrection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Clock Correction (s)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='delay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sending Delay (ms)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='sensorintegrationtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sensor Integration Time (ms)'),
        ),
    ]
