# Generated by Django 3.0.8 on 2020-11-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0062_auto_20201117_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationAdvisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_app_depth', models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Net Application Depth (mm)')),
                ('irrigation_period', models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Irrigation Period (mins)')),
                ('irrigation_volume', models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Irrigation Volume (l)')),
                ('fieldunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit')),
            ],
            options={
                'verbose_name_plural': 'Computation: Basin',
            },
        ),
        migrations.RemoveField(
            model_name='bordercomp',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='dripcomp',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='furrowcomp',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='sprinklercomp',
            name='fieldunit',
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Curve cutoff 1'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Curve cutoff 2'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Curve cutoff 3'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='bln_single_lateral',
            field=models.BooleanField(verbose_name='Single Straight Lateral'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='emitters_per_plant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='No. of Emitters per Plant'),
        ),
        migrations.AlterField(
            model_name='drippara',
            name='irrigation_interval',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Irrigation Interval (days)'),
        ),
        migrations.DeleteModel(
            name='BasinComp',
        ),
        migrations.DeleteModel(
            name='BorderComp',
        ),
        migrations.DeleteModel(
            name='DripComp',
        ),
        migrations.DeleteModel(
            name='FurrowComp',
        ),
        migrations.DeleteModel(
            name='SprinklerComp',
        ),
    ]
