# Generated by Django 3.0.8 on 2020-11-24 07:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0063_auto_20201120_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedmsgs',
            name='fieldunit_number',
        ),
        migrations.RemoveField(
            model_name='receivedmsgs',
            name='receiver_number',
        ),
        migrations.RemoveField(
            model_name='receivedmsgs',
            name='sender_number',
        ),
        migrations.RemoveField(
            model_name='receivedmsgs',
            name='usk',
        ),
        migrations.RemoveField(
            model_name='sentmsgs',
            name='fieldunit_number',
        ),
        migrations.RemoveField(
            model_name='sentmsgs',
            name='receiver_number',
        ),
        migrations.RemoveField(
            model_name='sentmsgs',
            name='sender_number',
        ),
        migrations.RemoveField(
            model_name='sentmsgs',
            name='usk',
        ),
        migrations.AddField(
            model_name='receivedmsgs',
            name='sender',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='sentmsgs',
            name='recipient',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='msg',
            field=models.TextField(max_length=200, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date/Time Sent'),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='msg',
            field=models.TextField(max_length=200, verbose_name='Message'),
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
