# Generated by Django 3.0.8 on 2020-11-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0064_auto_20201124_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorNumber',
            new_name='Sensor',
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ('name',), 'verbose_name_plural': 'Site: Farms'},
        ),
        migrations.AlterModelOptions(
            name='moisturecontent',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'Site: Moisture Content'},
        ),
        migrations.RenameField(
            model_name='basinpara',
            old_name='basin_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='borderpara',
            old_name='num_of_border_strips',
            new_name='border_strips',
        ),
        migrations.RenameField(
            model_name='borderpara',
            old_name='border_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='borderpara',
            old_name='border_width',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='calibrationconstant',
            old_name='calib_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='farm_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fieldunit',
            old_name='numberofsamples',
            new_name='samples',
        ),
        migrations.RenameField(
            model_name='moisturecontent',
            old_name='sensor_name',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='receivedmsgs',
            old_name='sender',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sentmsgs',
            old_name='recipient',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='sensors',
        ),
        migrations.RemoveField(
            model_name='moisturecontent',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='moisturecontent',
            name='mc_data',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Analog Reading'),
        ),
        migrations.AddField(
            model_name='sentmsgs',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Sent?'),
        ),
    ]
