# Generated by Django 3.0.8 on 2020-11-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0065_auto_20201127_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name')),
                ('basin_length', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Basin Length (m)')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Border Width (m)')),
                ('border_strips', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Number of Borders')),
                ('mannings_coeff', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name="Manning's coefficient")),
                ('flow_rate_per_strip', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Flow rate per border strip (lps)')),
                ('total_flow_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Total flow rate (lps)')),
                ('bln_furrow_type', models.BooleanField(verbose_name='It is an open-ended furrow.')),
                ('discharge', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Unit Discharge (lps)')),
                ('area_slope', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Slope')),
                ('bln_single_lateral', models.BooleanField(verbose_name='Single Straight Lateral')),
                ('emitters_per_plant', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='No. of Emitters per Plant')),
                ('emitter_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Emitter Spacing (m)')),
                ('plant_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Plant spacing (m)')),
                ('row_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Row spacing (m)')),
                ('wetted_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wetted diameter (m)')),
                ('EU', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True, verbose_name='Design Emission Uniformity')),
                ('irrigation_interval', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Irrigation Interval (days)')),
                ('farm_area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Farm area (sq.m)')),
                ('area_irrigated_at_a_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Area irrigated at a time (sq.m)')),
                ('lateral_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lateral spacing (m)')),
                ('sprinkler_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler spacing (m)')),
                ('num_of_sprinklers', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Number of sprinklers')),
                ('ea', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency')),
                ('sprinkler_discharge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler Discharge (lps)')),
            ],
            options={
                'verbose_name_plural': 'Irrigation System',
            },
        ),
        migrations.AlterModelOptions(
            name='irrigationadvisory',
            options={'verbose_name_plural': 'Computation'},
        ),
        migrations.RemoveField(
            model_name='farm',
            name='basin_sys',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='border_sys',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='drip_sys',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='furrow_sys',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='sprinkler_sys',
        ),
        migrations.DeleteModel(
            name='BasinPara',
        ),
        migrations.DeleteModel(
            name='BorderPara',
        ),
        migrations.DeleteModel(
            name='DripPara',
        ),
        migrations.DeleteModel(
            name='FurrowPara',
        ),
        migrations.DeleteModel(
            name='SprinklerPara',
        ),
        migrations.AddField(
            model_name='farm',
            name='irrigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.IrrigationParameters', verbose_name='Irrigation'),
        ),
    ]
