# Generated by Django 3.0.8 on 2020-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0067_remove_irrigationparameters_sprinkler_discharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationparameters',
            old_name='name',
            new_name='name_basin',
        ),
        migrations.RemoveField(
            model_name='fieldunit',
            name='servernumber',
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='name_border',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='name_drip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='name_furrow',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='name_sprinkler',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Name'),
        ),
    ]
