# Generated by Django 3.0.8 on 2020-12-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0069_irrigationparameters_irrig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationparameters',
            old_name='name_basin',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='irrig',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='name_border',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='name_drip',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='name_furrow',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='name_sprinkler',
        ),
    ]
