# Generated by Django 3.0.8 on 2020-12-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0070_auto_20201203_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='calib_eqn',
        ),
        migrations.AddField(
            model_name='calibrationconstant',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AlterModelTable(
            name='fieldunit',
            table=None,
        ),
    ]
