# Generated by Django 3.0.8 on 2020-12-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0071_auto_20201207_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moisturecontent',
            name='fieldunit',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
    ]
