# Generated by Django 3.0.8 on 2020-12-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0072_auto_20201207_1749'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor',
            table=None,
        ),
    ]
