# Generated by Django 3.0.8 on 2020-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0073_auto_20201208_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Depth, m'),
        ),
    ]
