# Generated by Django 3.0.8 on 2020-12-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0074_auto_20201208_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moisturecontent',
            name='mc_data',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Analog Reading'),
        ),
        migrations.AlterField(
            model_name='moisturecontent',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Sensor'),
        ),
        migrations.AlterField(
            model_name='moisturecontent',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='Date & Time Measured'),
        ),
    ]
