# Generated by Django 3.0.8 on 2021-01-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0076_auto_20210105_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmsgs',
            name='msg',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel'),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='msg',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel'),
        ),
    ]
