# Generated by Django 3.0.8 on 2021-01-18 07:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0077_auto_20210108_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmsgs',
            name='marker',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=11, null=True, region=None),
        ),
    ]
