# Generated by Django 3.0.8 on 2021-01-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0080_auto_20210128_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedmsgs',
            old_name='fieldunit',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='sentmsgs',
            old_name='fieldunit',
            new_name='mobilenumber',
        ),
    ]
