# Generated by Django 3.0.8 on 2021-01-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0081_auto_20210128_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedmsgs',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='sentmsgs',
            name='mobilenumber',
        ),
    ]
