# Generated by Django 3.0.8 on 2021-02-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0084_auto_20210128_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_manager',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='fieldunit',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='intakefamily',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='irrigation',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='soil',
        ),
        migrations.CreateModel(
            name='WAISSystems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=20)),
                ('calib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.CalibrationConstant', verbose_name='Intake Family')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Crop')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm', verbose_name='Manager')),
                ('farm_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel', verbose_name='Manager')),
                ('fieldunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit')),
                ('irrigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.IrrigationParameters', verbose_name='Irrigation')),
                ('soil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Soil')),
            ],
            options={
                'verbose_name_plural': 'Site: Farms',
                'ordering': ('system_name',),
            },
        ),
    ]
