# Generated by Django 3.0.8 on 2021-02-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0086_auto_20210215_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ('last_name',), 'verbose_name_plural': 'Site: Farm Managers'},
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, help_text='Application efficiency is the fraction of the irrigation water that is used by the crop. Provided there are no runoff losses, the application efficiency (%) is the required irrigation depth (mm), divided by the average applied irrigation depth (mm), multiplied by 100%.', max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
    ]
