# Generated by Django 3.0.8 on 2021-02-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0087_auto_20210216_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_equation',
            field=models.CharField(choices=[('LIN', 'Linear'), ('QUA', 'Quadratic'), ('EXP', 'Exponential'), ('LOG', 'Logarithmic'), ('SSIG', 'Symmetrical Sigmoidal'), ('ASSIG', 'Asymmetrical Sigmoidal')], default='LIN', max_length=5, verbose_name='Equation Form'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Field Unit Number'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='number',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='calib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.CalibrationConstant', verbose_name='Calibration Equation'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel', verbose_name='Farm Manager'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='irrigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.IrrigationParameters', verbose_name='Irrigation System'),
        ),
    ]
