# Generated by Django 3.0.8 on 2021-02-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0089_auto_20210217_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
