# Generated by Django 3.0.8 on 2021-02-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0090_auto_20210217_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedmsgs',
            name='fieldunit_number',
        ),
        migrations.RemoveField(
            model_name='sentmsgs',
            name='fieldunit_number',
        ),
    ]
