# Generated by Django 3.0.8 on 2021-02-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0093_auto_20210217_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationparameters',
            name='irrigation_system_type',
            field=models.CharField(blank=True, choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True),
        ),
    ]
