# Generated by Django 3.0.8 on 2021-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0094_irrigationparameters_irrigation_system_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldunit',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='fieldunit',
            name='longi',
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='irrigation_system_type',
            field=models.CharField(blank=True, choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True, verbose_name='Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Irrigation System Name'),
        ),
    ]
