# Generated by Django 3.0.8 on 2021-02-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0096_auto_20210223_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_equation',
            field=models.CharField(choices=[('linear', 'Linear'), ('quadratic', 'Quadratic'), ('exponential', 'Exponential'), ('logarithmic', 'Logarithmic'), ('symmetrical sigmoidal', 'Symmetrical Sigmoidal'), ('asymmetrical sigmoidal', 'Asymmetrical Sigmoidal')], default='linear', max_length=30, verbose_name='Equation Form'),
        ),
    ]
