# Generated by Django 3.0.8 on 2021-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0098_auto_20210225_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='intake_family',
            field=models.CharField(blank=True, choices=[('clay_005)', 'clay (0.5)'), ('clay_01', 'clay (0.1)'), ('clay_015', 'clay (0.15)'), ('clay_loam_02', 'clay loam (0.2)'), ('clay_loam_025', 'clay loam (0.25)'), ('clay_loam_03', 'clay loam (0.3)'), ('silty_035', 'silty (0.35)'), ('silty_04', 'silty (0.4)'), ('silty_loam_045', 'silty loam (0.45)'), ('silty_loam_05', 'silty loam (0.5)'), ('silty_loam_06', 'silty loam (0.6)'), ('silty_loam_07', 'silty loam (0.7)'), ('sandy_loam_08', 'sandy loam (0.8)'), ('sandy_loam_09', 'sandy loam (0.9)'), ('sandy_loam_10', 'sandy loam (1.0)'), ('sandy_15', 'sandy (1.5)'), ('sandy_20', 'sandy (2.0)')], help_text='The number indicates the intake rate of the soil. Required for surface irrigations- basin, border, and furrow.', max_length=30, null=True, verbose_name='Intake Family'),
        ),
    ]
