# Generated by Django 3.0.8 on 2021-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0099_auto_20210225_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationparameters',
            name='ea',
            field=models.DecimalField(blank=True, choices=[(0.5, '0.50'), (0.55, '0.55'), (0.6, '0.60'), (0.7, '0.70'), (0.75, '0.75'), (0.8, '0.80'), (0.85, '0.85'), (0.9, '0.90'), (0.95, '0.95')], decimal_places=2, help_text='Application efficiency is the fraction of the irrigation water that is used by the crop. Provided there are no runoff losses, the application efficiency (%) is the required irrigation depth (mm), divided by the average applied irrigation depth (mm), multiplied by 100%.', max_digits=5, null=True, verbose_name='Application Efficiency'),
        ),
    ]
