# Generated by Django 3.0.8 on 2021-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0100_auto_20210225_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='fcoarser_rate_per_strip',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='total_fcoarser_rate',
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='flow_rate_per_strip',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Flow rate per border strip (lps)'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='total_flow_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Total flow rate (lps)'),
        ),
    ]
