# Generated by Django 3.0.8 on 2021-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0101_auto_20210225_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationparameters',
            name='border_length',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Border Length (m)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='ea',
            field=models.DecimalField(blank=True, choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, help_text='Application efficiency is the fraction of the irrigation water that is used by the crop. Provided there are no runoff losses, the application efficiency (%) is the required irrigation depth (mm), divided by the average applied irrigation depth (mm), multiplied by 100%.', max_digits=5, null=True, verbose_name='Application Efficiency'),
        ),
    ]
