# Generated by Django 3.0.8 on 2021-02-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0102_auto_20210226_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationparameters',
            name='furrow_length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Furrow Length'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='furrow_spacing',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Furrow Spacing'),
        ),
    ]
