# Generated by Django 3.0.8 on 2021-02-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0103_auto_20210226_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationparameters',
            name='emitter_discharge',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Emitter Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='furrow_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Furrow Length'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='furrow_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Furrow Spacing'),
        ),
    ]
