# Generated by Django 3.0.8 on 2021-02-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0104_auto_20210226_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentShaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_shaded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Area Shaded (%)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Crop', verbose_name='Crop')),
            ],
        ),
    ]
