# Generated by Django 3.0.8 on 2021-02-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0105_percentshaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percentshaded',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'Site: Percent Area Shaded'},
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='bln_ii',
            field=models.BooleanField(default=False, verbose_name='Has preferred irrigation interval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='peak_Etcrop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peak Evapotranspiration (mm/day)'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='transpiration_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Transpiration Ratio'),
        ),
    ]
