# Generated by Django 3.0.8 on 2021-02-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0106_auto_20210226_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='peak_Etcrop',
        ),
        migrations.AddField(
            model_name='crop',
            name='peak_Etcrop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peak Evapotranspiration (mm/day)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='bln_furrow_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='It is an open-ended furrow.'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='bln_ii',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has preferred irrigation interval'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='bln_single_lateral',
            field=models.BooleanField(blank=True, null=True, verbose_name='Single Straight Lateral'),
        ),
    ]
