# Generated by Django 3.0.8 on 2021-02-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0107_auto_20210226_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='transpiration_ratio',
        ),
        migrations.AddField(
            model_name='crop',
            name='transpiration_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Transpiration Ratio'),
        ),
    ]
