# Generated by Django 3.0.8 on 2021-03-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0108_auto_20210226_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationparameters',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basin, Furrow, Border', max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='emitter_discharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Drip', max_digits=5, null=True, verbose_name='Emitter Discharge (l/day)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='farm_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Farm area (sq.m)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='irrigation_interval',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Input only if you have preferred irrigation interval based on your farm schedule.', max_digits=5, null=True, verbose_name='Irrigation Interval (days)'),
        ),
    ]
