# Generated by Django 3.0.8 on 2021-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0109_auto_20210301_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='area_irrigated_at_a_time',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='farm_area',
        ),
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='num_of_sprinklers',
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='bln_sprinkler_discharge',
            field=models.BooleanField(blank=True, null=True, verbose_name='Compute Sprinkler Discharge'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='discharge_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.95 - 0.98', max_digits=5, null=True, verbose_name='Discharge Coefficient'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='nozzle_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nozzle Diameter (cm)'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='operating_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Operating Pressure (kPa)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='mad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Management Allowable Deficit'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='peak_Etcrop',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='required for drip irrigation system only', max_digits=5, null=True, verbose_name='Peak Evapotranspiration (mm/day)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='transpiration_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='required for drip irrigation system only', max_digits=5, null=True, verbose_name='Transpiration Ratio'),
        ),
    ]
