# Generated by Django 3.0.8 on 2021-03-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0110_auto_20210301_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='As',
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='nozzle_diameter',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Nozzle Diameter (cm)'),
        ),
    ]
