# Generated by Django 3.0.8 on 2021-03-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0112_auto_20210302_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waissystems',
            options={'get_latest_by': 'timestamp', 'ordering': ('name',), 'verbose_name_plural': 'WAISSystems'},
        ),
        migrations.AddField(
            model_name='waissystems',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='area_slope',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='(Furrow, Border)', max_digits=20, null=True, verbose_name='Slope (m/m)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(Basin, Furrow, Border, Sprinkler)', max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='ea',
            field=models.DecimalField(blank=True, choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, help_text='Basin, Sprinkler', max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='emitter_discharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(Drip)', max_digits=5, null=True, verbose_name='Emitter Discharge (l/day)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='irrigation_interval',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Fillout only if you have preferred irrigation interval based on your farm schedule.', max_digits=5, null=True, verbose_name='Irrigation Interval (days)'),
        ),
        migrations.AlterField(
            model_name='irrigationparameters',
            name='mannings_coeff',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='(Furrow, Border)', max_digits=20, null=True, verbose_name="Manning's coefficient"),
        ),
    ]
