# Generated by Django 3.0.8 on 2021-03-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0113_auto_20210304_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrrigationAdvisory',
        ),
    ]
