# Generated by Django 3.0.8 on 2021-03-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0114_delete_irrigationadvisory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationconstant',
            options={'verbose_name_plural': 'Calibration Equations'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ('crop',), 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ('name',), 'verbose_name_plural': 'Farms'},
        ),
        migrations.AlterModelOptions(
            name='fieldunit',
            options={'verbose_name_plural': 'Field Units'},
        ),
        migrations.AlterModelOptions(
            name='moisturecontent',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'Moisture Content'},
        ),
        migrations.AlterModelOptions(
            name='percentshaded',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'Percent Area Shaded'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ('last_name',), 'verbose_name_plural': 'Farm Managers'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='soil',
            options={'ordering': ('soiltype',), 'verbose_name_plural': 'Soil'},
        ),
        migrations.AddField(
            model_name='moisturecontent',
            name='rainfall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rainfall (mm)'),
        ),
    ]
