# Generated by Django 3.0.8 on 2021-03-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0115_auto_20210309_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moisturecontent',
            name='rainfall',
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rainfall (mm)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time Sent')),
                ('fieldunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit')),
            ],
        ),
    ]
