# Generated by Django 3.0.8 on 2021-03-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0118_gravimetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (med)'),
        ),
        migrations.AlterField(
            model_name='gravimetric',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit'),
        ),
        migrations.AlterField(
            model_name='gravimetric',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
