# Generated by Django 3.0.8 on 2021-03-22 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waissapp', '0120_waissystems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waissystems',
            name='user',
        ),
        migrations.AddField(
            model_name='calibrationconstant',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationconstant',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crop',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receivedmsgs',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivedmsgs',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sentmsgs',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentmsgs',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soil',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waissystems',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waissystems',
            name='personal',
            field=models.BooleanField(default=True),
        ),
    ]
