# Generated by Django 3.0.8 on 2021-03-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0121_auto_20210322_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
    ]
