# Generated by Django 3.0.8 on 2021-03-22 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waissapp', '0122_crop_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='personal',
            field=models.BooleanField(default=True),
        ),
    ]
