# Generated by Django 3.0.8 on 2021-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0123_auto_20210322_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
