# Generated by Django 3.0.8 on 2021-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0124_auto_20210326_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationconstant',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
    ]
