# Generated by Django 3.0.8 on 2021-04-20 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waissapp', '0125_auto_20210326_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldunit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Unit Name'),
        ),
        migrations.CreateModel(
            name='Sprinkler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('discharge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)')),
                ('ea', models.DecimalField(blank=True, choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, help_text='Basin, Sprinkler', max_digits=5, null=True, verbose_name='Application Efficiency (%)')),
                ('lateral_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lateral spacing (m)')),
                ('sprinkler_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler spacing (m)')),
                ('bln_sprinkler_discharge', models.BooleanField(blank=True, null=True, verbose_name='Compute Sprinkler Discharge')),
                ('nozzle_diameter', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Nozzle Diameter (cm)')),
                ('operating_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Operating Pressure (kPa)')),
                ('discharge_coefficient', models.DecimalField(blank=True, decimal_places=2, help_text='0.95 - 0.98', max_digits=5, null=True, verbose_name='Discharge Coefficient')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('personal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sprinkler Irrigation System',
            },
        ),
        migrations.CreateModel(
            name='Furrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('discharge', models.DecimalField(blank=True, decimal_places=2, help_text='(Basin, Furrow, Border, Sprinkler)', max_digits=20, null=True, verbose_name='Unit Discharge (lps)')),
                ('mannings_coeff', models.DecimalField(blank=True, decimal_places=4, help_text='(Furrow, Border)', max_digits=20, null=True, verbose_name="Manning's coefficient")),
                ('area_slope', models.DecimalField(blank=True, decimal_places=4, help_text='(Furrow, Border)', max_digits=20, null=True, verbose_name='Slope (m/m)')),
                ('bln_furrow_type', models.BooleanField(blank=True, null=True, verbose_name='It is an open-ended furrow.')),
                ('furrow_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Furrow Spacing')),
                ('furrow_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Furrow Length')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('personal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Furrow Irrigation System',
            },
        ),
        migrations.CreateModel(
            name='Drip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('bln_single_lateral', models.BooleanField(blank=True, null=True, verbose_name='Single Straight Lateral')),
                ('discharge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Emitter Discharge (l/day)')),
                ('emitters_per_plant', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='No. of Emitters per Plant')),
                ('emitter_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Emitter Spacing (m)')),
                ('plant_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Plant spacing (m)')),
                ('row_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Row spacing (m)')),
                ('wetted_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wetted diameter (m)')),
                ('bln_ii', models.BooleanField(blank=True, null=True, verbose_name='Has preferred irrigation interval')),
                ('irrigation_interval', models.DecimalField(blank=True, decimal_places=0, help_text='Fillout only if you have preferred irrigation interval based on your farm schedule.', max_digits=5, null=True, verbose_name='Irrigation Interval (days)')),
                ('EU', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True, verbose_name='Design Emission Uniformity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('personal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Drip Irrigation System',
            },
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('discharge', models.DecimalField(blank=True, decimal_places=2, help_text='(Basin, Furrow, Border, Sprinkler)', max_digits=20, null=True, verbose_name='Unit Discharge (lps)')),
                ('mannings_coeff', models.DecimalField(blank=True, decimal_places=4, help_text='(Furrow, Border)', max_digits=20, null=True, verbose_name="Manning's coefficient")),
                ('area_slope', models.DecimalField(blank=True, decimal_places=4, help_text='(Furrow, Border)', max_digits=20, null=True, verbose_name='Slope (m/m)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('personal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Border Irrigation System',
            },
        ),
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('discharge', models.DecimalField(blank=True, decimal_places=2, help_text='(Basin, Furrow, Border, Sprinkler)', max_digits=20, null=True, verbose_name='Unit Discharge (lps)')),
                ('basin_length', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Basin Length (m)')),
                ('ea', models.DecimalField(blank=True, choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, help_text='Basin, Sprinkler', max_digits=5, null=True, verbose_name='Application Efficiency (%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('personal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Basin Irrigation System',
            },
        ),
    ]
