# Generated by Django 3.0.8 on 2021-04-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0126_auto_20210420_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='waissystems',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Basin', verbose_name='Irrigation System'),
        ),
        migrations.AddField(
            model_name='waissystems',
            name='border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Border', verbose_name='Irrigation System'),
        ),
        migrations.AddField(
            model_name='waissystems',
            name='drip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Drip', verbose_name='Irrigation System'),
        ),
        migrations.AddField(
            model_name='waissystems',
            name='furrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Furrow', verbose_name='Irrigation System'),
        ),
        migrations.AddField(
            model_name='waissystems',
            name='sprinkler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Sprinkler', verbose_name='Irrigation System'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='ea',
            field=models.DecimalField(blank=True, choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='area_slope',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Slope (m/m)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='mannings_coeff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name="Manning's coefficient"),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='area_slope',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Slope (m/m)'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='mannings_coeff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name="Manning's coefficient"),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='discharge_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Common values: 0.95 - 0.98', max_digits=5, null=True, verbose_name='Discharge Coefficient'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='ea',
            field=models.DecimalField(blank=True, choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
    ]
