# Generated by Django 3.0.8 on 2021-04-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0127_auto_20210421_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basin',
            options={'verbose_name_plural': 'Irrigation System: Basin'},
        ),
        migrations.AlterModelOptions(
            name='border',
            options={'verbose_name_plural': 'Irrigation System: Border'},
        ),
        migrations.AlterModelOptions(
            name='drip',
            options={'verbose_name_plural': 'Irrigation System: Drip'},
        ),
        migrations.AlterModelOptions(
            name='furrow',
            options={'verbose_name_plural': 'Irrigation System: Furrow'},
        ),
        migrations.AlterModelOptions(
            name='sprinkler',
            options={'verbose_name_plural': 'Irrigation System: Sprinkler'},
        ),
        migrations.RemoveField(
            model_name='waissystems',
            name='irrigation',
        ),
        migrations.DeleteModel(
            name='IrrigationParameters',
        ),
    ]
