# Generated by Django 3.0.8 on 2021-04-29 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waissapp', '0128_auto_20210421_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensor',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Basin', verbose_name='Basin System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Border', verbose_name='Border System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='drip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Drip', verbose_name='Drip System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='furrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Furrow', verbose_name='Furrow System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='sprinkler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Sprinkler', verbose_name='Sprinkler System'),
        ),
    ]
