# Generated by Django 3.0.8 on 2021-05-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0129_auto_20210429_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basin',
            options={'verbose_name_plural': '5.a. Irrigation System: Basin'},
        ),
        migrations.AlterModelOptions(
            name='border',
            options={'verbose_name_plural': '5.b. Irrigation System: Border'},
        ),
        migrations.AlterModelOptions(
            name='calibrationconstant',
            options={'verbose_name_plural': '7. Calibration Equations'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ('crop',), 'verbose_name_plural': '3. Crops'},
        ),
        migrations.AlterModelOptions(
            name='drip',
            options={'verbose_name_plural': '5.e. Irrigation System: Drip'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ('name',), 'verbose_name_plural': '1. Farms'},
        ),
        migrations.AlterModelOptions(
            name='fieldunit',
            options={'verbose_name_plural': '6. Field Units'},
        ),
        migrations.AlterModelOptions(
            name='furrow',
            options={'verbose_name_plural': '5.c. Irrigation System: Furrow'},
        ),
        migrations.AlterModelOptions(
            name='moisturecontent',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': '9. Moisture Content'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ('last_name',), 'verbose_name_plural': '2. Farm Managers'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': '8. Sensors'},
        ),
        migrations.AlterModelOptions(
            name='soil',
            options={'ordering': ('soiltype',), 'verbose_name_plural': '4. Soil'},
        ),
        migrations.AlterModelOptions(
            name='sprinkler',
            options={'verbose_name_plural': '5.d. Irrigation System: Sprinkler'},
        ),
        migrations.AlterModelOptions(
            name='waissystems',
            options={'get_latest_by': 'timestamp', 'ordering': ('name',), 'verbose_name_plural': '0. WAISSystems'},
        ),
    ]
