# Generated by Django 3.0.8 on 2021-05-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0130_auto_20210503_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='date_transplanted',
        ),
        migrations.AddField(
            model_name='waissystems',
            name='date_transplanted',
            field=models.DateField(null=True, verbose_name='Date Transplanted'),
        ),
    ]
