# Generated by Django 3.0.8 on 2021-05-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0132_auto_20210527_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='lat',
            field=models.CharField(blank='True', max_length=50, null='True', verbose_name='Latitude'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='farm',
            name='long',
            field=models.CharField(blank='True', max_length=50, null='True', verbose_name='Longitude'),
            preserve_default='True',
        ),
    ]
