# Generated by Django 3.0.8 on 2021-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0132_auto_20210511_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='area_slope',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Slope (m/m)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='mannings_coeff',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name="Manning's coefficient"),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='area_slope',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Slope (m/m)'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='bln_furrow_type',
            field=models.BooleanField(null=True, verbose_name='It is an open-ended furrow.'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='furrow_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Furrow Length'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='furrow_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Furrow Spacing'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='mannings_coeff',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name="Manning's coefficient"),
        ),
    ]
