# Generated by Django 3.0.8 on 2021-05-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0133_auto_20210527_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='basin_length',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Basin Length (m)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='border',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_a',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_b',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='peak_Etcrop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peak Evapotranspiration (mm/day)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='transpiration_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Transpiration Ratio'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Depth, m'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soiltype',
            field=models.CharField(max_length=25, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='lateral_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Lateral spacing (m)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='sprinkler_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sprinkler spacing (m)'),
        ),
    ]
