# Generated by Django 3.0.8 on 2021-05-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0134_auto_20210527_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='timestamp',
        ),
    ]
