# Generated by Django 3.0.8 on 2021-06-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0135_auto_20210528_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationconstant',
            options={'ordering': ('name',), 'verbose_name_plural': '7. Calibration Equations'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'get_latest_by': 'timestamp', 'ordering': ('name',), 'verbose_name_plural': '1. Farms'},
        ),
        migrations.AlterModelOptions(
            name='fieldunit',
            options={'ordering': ('name',), 'verbose_name_plural': '6. Field Units'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('name',), 'verbose_name_plural': '8. Sensors'},
        ),
        migrations.AlterField(
            model_name='basin',
            name='basin_length',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True, verbose_name='Basin Length (m)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_growth_model',
            field=models.CharField(choices=[('Borg-Grimes Model', 'Borg-Grimes Model'), ('User-Defined', 'User-Defined'), ('Inverse Kc', 'Inverse Kc')], help_text='Fillout additional information below.', max_length=30, null=True, verbose_name='Root Growth Model'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soiltype',
            field=models.CharField(max_length=25, verbose_name='Soil'),
        ),
    ]
