# Generated by Django 3.0.8 on 2021-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0136_auto_20210604_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kc (mid)'),
        ),
        migrations.AlterField(
            model_name='moisturecontent',
            name='mc_data',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='Analog Reading'),
        ),
    ]
