# Generated by Django 3.0.8 on 2021-07-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0137_auto_20210701_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentshaded',
            name='crop',
        ),
        migrations.AddField(
            model_name='percentshaded',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Crop'),
        ),
    ]
