# Generated by Django 3.0.8 on 2021-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0138_auto_20210706_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='intake_family',
            field=models.CharField(blank=True, choices=[('clay (0.05)', 'clay (0.5)'), ('clay (0.1)', 'clay (0.1)'), ('clay (0.15)', 'clay (0.15)'), ('clay loam (0.2)', 'clay loam (0.2)'), ('clay loam (0.25)', 'clay loam (0.25)'), ('clay loam (0.3)', 'clay loam (0.3)'), ('silty (0.35)', 'silty (0.35)'), ('silty (0.4)', 'silty (0.4)'), ('silty loam (0.45)', 'silty loam (0.45)'), ('silty loam (0.5)', 'silty loam (0.5)'), ('silty loam (0.6)', 'silty loam (0.6)'), ('silty loam (0.7)', 'silty loam (0.7)'), ('sandy loam (0.8)', 'sandy loam (0.8)'), ('sandy loam (0.9)', 'sandy loam (0.9)'), ('sandy loam (1.0)', 'sandy loam (1.0)'), ('sandy (1.5)', 'sandy (1.5)'), ('sandy (2.0)', 'sandy (2.0)')], help_text='The number indicates the intake rate of the soil. Required for surface irrigations- basin, border, and furrow.', max_length=30, null=True, verbose_name='Intake Family'),
        ),
    ]
