# Generated by Django 3.0.8 on 2021-07-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0139_auto_20210706_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='brgy',
            field=models.CharField(max_length=50, null='True', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='municipality',
            field=models.CharField(max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=20, unique='True'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='province',
            field=models.CharField(max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='clockcorrection',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Clock Correction (s)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='delay',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Sending Delay (ms)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='samples',
            field=models.DecimalField(blank=True, decimal_places=0, default=10, max_digits=3, null=True, verbose_name='No. of Samples'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='sensorintegrationtime',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Sensor Integration Time (ms)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='timestart',
            field=models.TimeField(blank=True, default=8, null=True, verbose_name='Starting Time'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='timestop',
            field=models.TimeField(blank=True, default=17, null=True, verbose_name='Stopping Time'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='date_transplanted',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Transplanted'),
        ),
    ]
