# Generated by Django 3.0.8 on 2021-07-13 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0140_auto_20210713_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldunit',
            name='automaticthreshold',
            field=models.BooleanField(verbose_name='Automatic Threshold (?)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='clockcorrection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Clock Correction (s)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='delay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sending Delay (ms)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='fieldunitstatus',
            field=models.BooleanField(verbose_name='Field Unit Status'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Field Unit Name'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='samples',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='No. of Samples'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='sensorintegrationtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sensor Integration Time (ms)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='timestart',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting Time'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='timestop',
            field=models.TimeField(blank=True, null=True, verbose_name='Stopping Time'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='withirrigation',
            field=models.BooleanField(verbose_name='With Irrigation (?)'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
    ]
