# Generated by Django 3.0.8 on 2021-07-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0141_auto_20210713_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Sensor Name'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soiltype',
            field=models.CharField(max_length=25, unique=True, verbose_name='Soil'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
