# Generated by Django 3.0.8 on 2021-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0143_auto_20210716_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='root_growth_model',
            field=models.CharField(choices=[('Borg-Grimes Model', 'Borg-Grimes Model'), ('User-Defined', 'User-Defined'), ('Inverse Kc', 'Inverse Kc')], max_length=30, null=True, verbose_name='Root Growth Model'),
        ),
    ]
