# Generated by Django 3.0.8 on 2021-07-19 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0144_auto_20210719_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waissystems',
            name='calib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.CalibrationConstant', verbose_name='Calibration Equation'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Crop'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='date_transplanted',
            field=models.DateField(blank=True, null=True, verbose_name='Date Transplanted'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Personnel', verbose_name='Farm Manager'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waissapp.Soil'),
        ),
    ]
