# Generated by Django 3.0.8 on 2021-07-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0145_auto_20210719_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprinkler',
            name='bln_sprinkler_discharge',
        ),
        migrations.RemoveField(
            model_name='sprinkler',
            name='discharge_coefficient',
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='date_transplanted',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Transplanted'),
        ),
    ]
