# Generated by Django 3.0.8 on 2021-07-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0146_auto_20210720_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='basin',
            name='bln_irrigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basin',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drips')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
        migrations.AddField(
            model_name='border',
            name='bln_irrigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='border',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drips')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
        migrations.AddField(
            model_name='crop',
            name='bln_drip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drip',
            name='bln_irrigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drip',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drips')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
        migrations.AddField(
            model_name='farm',
            name='bln_coordinates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='furrow',
            name='bln_irrigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='furrow',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drips')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
        migrations.AddField(
            model_name='soil',
            name='bln_surface_irrigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprinkler',
            name='bln_irrigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprinkler',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drips')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
    ]
