# Generated by Django 3.0.8 on 2021-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0147_auto_20210727_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='bln_coordinates',
        ),
        migrations.AddField(
            model_name='farm',
            name='select_coordinates',
            field=models.CharField(choices=[('yes', 'Yes, I do!'), ('no', 'No, I dont.')], max_length=3, null='True', verbose_name='Do you have the coordinates of your farm?'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='basin',
            name='bln_irrigation',
            field=models.BooleanField(default=False, verbose_name='Do you have an irrigation system?'),
        ),
    ]
