# Generated by Django 3.0.8 on 2021-07-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0148_auto_20210727_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='bln_drip',
        ),
        migrations.AddField(
            model_name='crop',
            name='select_drip',
            field=models.CharField(choices=[('yes', 'Yes, I do!'), ('no', 'No, I dont.')], max_length=3, null='True', verbose_name='Are you going to use a drip irrigation system?'),
            preserve_default='True',
        ),
    ]
