# Generated by Django 3.0.8 on 2021-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0149_auto_20210727_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='bln_irrigation',
            field=models.CharField(choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null='True', verbose_name='Do you have an irrigation system?'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='select_drip',
            field=models.CharField(choices=[('yes', 'Yes, I will!'), ('no', 'No, I wont.')], max_length=3, null='True', verbose_name='Are you going to use a drip irrigation system?'),
        ),
    ]
