# Generated by Django 3.0.8 on 2021-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0150_auto_20210727_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drips')], max_length=30, null=True, verbose_name='Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='border',
            name='bln_irrigation',
            field=models.CharField(choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null='True', verbose_name='Do you have an irrigation system?'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='bln_irrigation',
            field=models.CharField(choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null='True', verbose_name='Do you have an irrigation system?'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='bln_irrigation',
            field=models.CharField(choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null='True', verbose_name='Do you have an irrigation system?'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='bln_irrigation',
            field=models.CharField(choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null='True', verbose_name='Do you have an irrigation system?'),
        ),
    ]
