# Generated by Django 3.0.8 on 2021-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0151_auto_20210727_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='ea',
            field=models.DecimalField(choices=[('50', '50'), ('55', '55'), ('60', '60'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True, verbose_name='Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='calib_equation',
            field=models.CharField(choices=[('linear', 'Linear'), ('quadratic', 'Quadratic'), ('exponential', 'Exponential'), ('logarithmic', 'Logarithmic'), ('symmetrical sigmoidal', 'Symmetrical Sigmoidal'), ('asymmetrical sigmoidal', 'Asymmetrical Sigmoidal')], max_length=30, null=True, verbose_name='Equation Form'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='ea',
            field=models.DecimalField(choices=[('50', '50'), ('55', '55'), ('60', '60'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
    ]
