# Generated by Django 3.0.8 on 2021-07-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0152_auto_20210729_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='select_irrigation',
            field=models.CharField(choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True, verbose_name='Select Irrigation System Type'),
        ),
    ]
