# Generated by Django 3.0.8 on 2021-08-03 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waissapp', '0154_auto_20210729_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basin',
            name='bln_irrigation',
            field=models.CharField(blank=True, choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null=True, verbose_name='Do you have an irrigation system?'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='select_irrigation',
            field=models.CharField(blank=True, choices=[('basin', 'basin'), ('border', 'border'), ('furrow', 'furrow'), ('sprinkler', 'sprinkler'), ('drip', 'drip')], max_length=30, null=True, verbose_name='Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='border',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='border',
            name='bln_irrigation',
            field=models.CharField(blank=True, choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null=True, verbose_name='Do you have an irrigation system?'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crop',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drip',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='select_coordinates',
            field=models.CharField(blank=True, choices=[('yes', 'Yes, I do!'), ('no', 'No, I dont.')], max_length=3, null='True', verbose_name='Do you have the coordinates of your farm?'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Field Unit Name'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Field Unit Number'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='usk',
            field=models.CharField(max_length=8, null=True, verbose_name='Unique Security Key'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gravimetric',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit'),
        ),
        migrations.AlterField(
            model_name='moisturecontent',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Sensor'),
        ),
        migrations.AlterField(
            model_name='percentshaded',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receivedmsgs',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Personnel'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentmsgs',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Personnel'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soil',
            name='bln_surface_irrigation',
            field=models.CharField(blank=True, choices=[('yes', 'Yes, I will!'), ('no', 'No, I wont.')], max_length=3, null='True', verbose_name='Are you going to use a surface irrigation system (e.g. basin, border, furrow)?'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Basin', verbose_name='Basin System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Border', verbose_name='Border System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='calib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.CalibrationConstant', verbose_name='Calibration Equation'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Crop'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='date_transplanted',
            field=models.DateField(blank=True, null=True, verbose_name='Date Transplanted'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='drip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Drip', verbose_name='Drip System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='farm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Personnel', verbose_name='Farm Manager'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='fieldunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='furrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Furrow', verbose_name='Furrow System'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Soil'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='sprinkler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Sprinkler', verbose_name='Sprinkler System'),
        ),
    ]
