# Generated by Django 3.0.8 on 2021-08-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0156_auto_20210803_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='waissystems',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='bln_ii',
            field=models.CharField(choices=[('yes', 'Yes, I do!'), ('no', 'No, I dont.')], max_length=6, null=True, verbose_name='Has preferred irrigation interval'),
        ),
        migrations.AlterField(
            model_name='gravimetric',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='moisturecontent',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='Date & Time Measured'),
        ),
    ]
