# Generated by Django 3.0.8 on 2021-08-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0157_auto_20210812_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rainfall',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'Rainfall'},
        ),
        migrations.AlterModelOptions(
            name='waissystems',
            options={'get_latest_by': 'modified_date', 'ordering': ('name',), 'verbose_name_plural': '0. WAISSystems'},
        ),
        migrations.AlterField(
            model_name='gravimetric',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='percentshaded',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='calib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.CalibrationConstant', verbose_name='Calibration Equation'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Crop'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='date_transplanted',
            field=models.DateField(null=True, verbose_name='Date Transplanted'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='farm_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Personnel', verbose_name='Farm Manager'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='fieldunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.FieldUnit', verbose_name='Field Unit'),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='waissystems',
            name='soil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Soil'),
        ),
    ]
