# Generated by Django 3.0.8 on 2021-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0158_auto_20210813_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='waissystems',
            name='checker',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='bln_surface_irrigation',
            field=models.CharField(choices=[('yes', 'Yes, I will!'), ('no', 'No, I wont.')], max_length=3, null='True', verbose_name='Are you going to use a surface irrigation system (e.g. basin, border, furrow)?'),
        ),
    ]
