# Generated by Django 3.0.8 on 2021-08-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0159_auto_20210817_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinkler',
            name='with_q_bln',
            field=models.CharField(blank=True, choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null='True', verbose_name='Do you know the sprinkler discharge?'),
            preserve_default='True',
        ),
    ]
