# Generated by Django 3.0.8 on 2021-08-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0160_sprinkler_with_q_bln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='irrigation_interval',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Irrigation Interval (days)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='bln_irrigation',
            field=models.CharField(blank=True, choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null=True, verbose_name='Do you have an irrigation system?'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='nozzle_diameter',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True, verbose_name='Nozzle Diameter (cm)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='operating_pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Operating Pressure (kPa)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='with_q_bln',
            field=models.CharField(choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null=True, verbose_name='Do you know the sprinkler discharge?'),
        ),
    ]
