# Generated by Django 3.0.8 on 2021-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0161_auto_20210826_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoIrrigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_area', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Farm Area (sq. m)')),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='select_coordinates',
            field=models.CharField(choices=[('yes', 'Yes, I do!'), ('no', 'No, I dont.')], max_length=3, null='True', verbose_name='Do you have the coordinates of your farm?'),
        ),
    ]
