# Generated by Django 3.0.8 on 2021-09-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0162_auto_20210906_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='noirrigation',
            name='farm',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waissapp.Farm'),
        ),
    ]
