# Generated by Django 3.0.8 on 2021-09-06 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0163_noirrigation_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='noirrigation',
            name='percent_covered',
            field=models.IntegerField(default=50, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Percentage of the Farm Area to be Irrigated'),
        ),
    ]
