# Generated by Django 3.2 on 2021-09-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0165_auto_20210906_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noirrigation',
            name='bln_irrigation',
            field=models.CharField(blank=True, choices=[('True', 'Yes, I do!'), ('False', 'No, I dont.')], max_length=6, null=True, verbose_name='Do you have an irrigation system?'),
        ),
    ]
