# Generated by Django 3.2 on 2021-09-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0166_alter_noirrigation_bln_irrigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waissystems',
            name='checker',
        ),
    ]
