# Generated by Django 3.2 on 2021-10-05 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0167_remove_waissystems_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='basin_length',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Basin Length (m)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='area_slope',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Slope (m/m)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='border',
            name='mannings_coeff',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name="Manning's coefficient"),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_a',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_b',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' c'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' d'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' m'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='date_tested',
            field=models.DateField(blank=True, null=True, verbose_name='Date Calibrated'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='drz',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Depth of Rootzone, m'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='growingperiod',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Growing Period, days'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Curve cutoff 1'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Curve cutoff 2'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_cc_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Curve cutoff 3'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2)], verbose_name='Kc (end)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2)], verbose_name='Kc (ini)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2)], verbose_name='Kc (mid)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='mad',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1)], verbose_name='Management Allowable Deficit'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='peak_Etcrop',
            field=models.DecimalField(blank=True, decimal_places=2, default=6.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Peak Evapotranspiration (mm/day)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_a',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_b',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_c',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name=' c'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Root Depth during Transplant (m)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='transpiration_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1)], verbose_name='Transpiration Ratio'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='EU',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Design Emission Uniformity'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Emitter Discharge (l/day)'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='emitter_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Emitter Spacing (m)'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='emitters_per_plant',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='No. of Emitters per Plant'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='irrigation_interval',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Irrigation Interval (days)'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='plant_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Plant spacing (m)'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='row_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Row spacing (m)'),
        ),
        migrations.AlterField(
            model_name='drip',
            name='wetted_dia',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Wetted diameter (m)'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='lat',
            field=models.DecimalField(blank='True', decimal_places=4, default=12.0, max_digits=6, null='True', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='long',
            field=models.DecimalField(blank='True', decimal_places=4, default=121.0, max_digits=7, null='True', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(130)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=50, unique='True', verbose_name='Farm Name'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='area_slope',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Slope (m/m)'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='furrow_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Furrow Length'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='furrow_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Furrow Spacing'),
        ),
        migrations.AlterField(
            model_name='furrow',
            name='mannings_coeff',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name="Manning's coefficient"),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Mobile Number (09)'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='fc',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Field Capacity (% vol)'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='pwp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Permanent Wilting Point (% vol)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='ea',
            field=models.DecimalField(choices=[(50, '50'), (55, '55'), (60, '60'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Application Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='lateral_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Lateral spacing (m)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='nozzle_diameter',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Nozzle Diameter (cm)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='operating_pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Operating Pressure (kPa)'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='sprinkler_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Sprinkler spacing (m)'),
        ),
    ]
