# Generated by Django 3.2 on 2021-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0168_auto_20211005_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='soiltype',
            field=models.CharField(max_length=30, unique=True, verbose_name='Soil'),
        ),
    ]
