# Generated by Django 3.2 on 2021-10-11 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0169_alter_soil_soiltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='basin_length',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Basin Length (m)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Mobile Number (09)'),
        ),
    ]
