# Generated by Django 3.2 on 2021-10-12 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waissapp', '0170_auto_20211011_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_area',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Farm Area (sq. m)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='basin_length',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Basin Length (m)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='discharge',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Discharge (lps)'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_a',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_b',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' c'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' d'),
        ),
        migrations.AlterField(
            model_name='calibrationconstant',
            name='coeff_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name=' m'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_a',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_b',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='root_c',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name=' c'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Data Source'),
        ),
        migrations.DeleteModel(
            name='NoIrrigation',
        ),
    ]
